# Generated by Django 5.0.3 on 2024-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_rename_exercises_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='training_type',
            field=models.CharField(choices=[('back_training', 'back_training'), ('chest_training', 'chest_training'), ('biceps_training', 'biceps_training'), ('triceps_training', 'triceps_training'), ('leg_training', 'leg_training'), ('glute_training', 'glute_training'), ('shoulder_training', 'shoulder_training')], default='back_training', max_length=20),
        ),
    ]
