# Generated by Django 5.0.3 on 2024-03-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exercise_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
    ]
